// <auto-generated />
namespace K9.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class K9UpdateJan01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(K9UpdateJan01));
        
        string IMigrationMetadata.Id
        {
            get { return "202101041918290_K9UpdateJan01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
