//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K9.Globalisation.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K9.Globalisation.Local.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessings.
        /// </summary>
        public static string Blessings {
            get {
                return ResourceManager.GetString("Blessings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	Iboga is now
        ///	an endangered species, classified in July 2000 as a ‘National Cultural Heritage
        ///	and Strategic Reserve’ by the Ex-President of Gabon, El Hadj Omar Bongo Ondimba.
        ///	Our organisation has been set up to preserve, research and share knowledge about
        ///	the medicinal plants and indigenous traditions of the Gabonese forest people for
        ///	the benefit of all of humanity. We are a &lt;a href=&quot;https://www.gov.uk/government/publications/community-interest-companies-introduction&quot;&gt;community interest compa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string blessings_of_the_forest {
            get {
                return ResourceManager.GetString("blessings_of_the_forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are many blessings of the forest, from the vast array of medicinal plants
        ///	of the Amazon, to less exotic but no less valuable varieties much closer to home.
        ///	However, few if any of nature&apos;s gifts are quite as precious as Iboga. .
        /// </summary>
        public static string blessings_of_the_forest_intro {
            get {
                return ResourceManager.GetString("blessings_of_the_forest_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our organisation has been set up to preserve, research and share knowledge about the medicinal plants and indigenous traditions of the Gabonese forest people for the benefit of all of humanity..
        /// </summary>
        public static string CompanyBlurbFooter {
            get {
                return ResourceManager.GetString("CompanyBlurbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessings Of The Forest C.I.C is a Community Interest Company, a Social Enterprise registered in England in October 2015 as a Company limited by shares (Company No:9816364)..
        /// </summary>
        public static string CompanyLegalDescription {
            get {
                return ResourceManager.GetString("CompanyLegalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5&gt;David Nassim, co-director of “Blessings Of The Forest” is a practitioner of Chinese medicine and internal martial arts. Since 1999 his studies include shiatsu, acupuncture, nutrition and herbal medicine, Qi Gong and Tai Chi Chuan.&lt;/h5&gt;
        ///&lt;p&gt;
        ///	He studied in several places around the world including the UK and Japan.
        ///	David is trained in permaculture and is involved in a self-sufficient community project in Europe (Portugal).
        ///	As part of his research in the field of traditional herbalism, he discovered  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string david_text {
            get {
                return ResourceManager.GetString("david_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-director of Blessings Of The Forest and practitioner of Chinese medicine.
        /// </summary>
        public static string david_title {
            get {
                return ResourceManager.GetString("david_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iboga has been sold in western world since 1901.
        ///						Today, more and more advertising touts iboga as a “miracle cure” without any apparent regard as to the sustainability of the resource.
        ///						Bought with gold, Iboga is then sold on the Internet in violation of laws protecting it, without equitable sharing of its benefits and a risk of consumers who have no certainty as to its origin and quality.
        ///						The price of iboga has increased by over 1000% in 15 years making this fundamental Gabonese medicine [rest of string was truncated]&quot;;.
        /// </summary>
        public static string iboga_text1 {
            get {
                return ResourceManager.GetString("iboga_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what can only be described as biopiracy, more than a dozen patents have been filed regarding the therapeutic use of iboga and its chemical derivatives in total disregard of the Nagoya Protocol protecting the people behind this plant and knowledge.
        ///The ivory trade and iboga trafficking are interlinked. Elephants love iboga fruit and the poachers track and kill them near the last wild reservations of iboga.
        ///Once they have murdered the elephants, the poachers also take all the iboga found on site.
        ///With y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string iboga_text2 {
            get {
                return ResourceManager.GetString("iboga_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pygmies have used iboga for over 65,000 years before it was discovered in the west.
        ///					Now, due to over-consumption without any policy of sustainable management, this sacred plant will disappear from the public domain within 5 years.
        /// </summary>
        public static string iboga_title1 {
            get {
                return ResourceManager.GetString("iboga_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessings Of The Forest is committed to building a bridge between traditional Gabonese healers and researchers worldwide. We offer humanity the most sacred knowledge of the art of healing using one of the most sacred plants of our common historic origins..
        /// </summary>
        public static string iboga_title2 {
            get {
                return ResourceManager.GetString("iboga_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iboga Gabon Medicine Healing Entheogen Ibogaine Addiction Transformation.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5&gt;Laurent Sazy is a french photojournalist since 1991. He is covering news, wars( Balkans, Sarajevo and caucasus, Algeria, Libya (2011), also politics, economics and socials news and magazines features for photos agencies, magazines and newspapers/&lt;/h5&gt;
        ///&lt;p&gt;
        ///	Laurent was photo-correspondent for The Européan Newspaper in Paris. He works with Sipa, Gamma, Maxppp, Deadline photo agency. In 2006, he joined Fedephoto which became in 2012, Divergence-images, a french plateform for press photographers.
        ///&lt;/p&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string laurent_text {
            get {
                return ResourceManager.GetString("laurent_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer and French photojournalist.
        /// </summary>
        public static string laurent_title {
            get {
                return ResourceManager.GetString("laurent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessings.
        /// </summary>
        public static string MainTitleLeft {
            get {
                return ResourceManager.GetString("MainTitleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of The Forest.
        /// </summary>
        public static string MainTitleRight {
            get {
                return ResourceManager.GetString("MainTitleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are our aims in relation to this plant considered as sacred by the Gabonese people.
        /// </summary>
        public static string mission_statement_and_aims_title1 {
            get {
                return ResourceManager.GetString("mission_statement_and_aims_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following aims of Blessings of the Forest do not focus on iboga, but are equally important.
        /// </summary>
        public static string mission_statement_and_aims_title2 {
            get {
                return ResourceManager.GetString("mission_statement_and_aims_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///	&lt;li&gt;&lt;i class=&quot;fa fa-angle-right&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Providing a voice in the world to explain the impact of the growing international interest for iboga on Gabonese traditions as well as the flora and fauna of Gabon&lt;/li&gt;
        ///	&lt;li&gt;&lt;i class=&quot;fa fa-angle-right&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Using legal expertise, in partnership with all Gabonese institutions and international organizations involved in the protection of biodiversity and traditional medicines, on ways and means to regulate the cultivation, ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mission_statement_and_aims1 {
            get {
                return ResourceManager.GetString("mission_statement_and_aims1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///	&lt;li&gt;&lt;i class=&quot;fa fa-angle-right&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Creating an eco-village with zero environmental impact.
        ///		The village will be powered by renewable energy systems such as wind and solar. It will also collect, filter, store and distribute rainwater. One or more wells will be drilled to make the village self-sufficient for water.
        ///		The houses in the village will be made with natural materials of the Gabonese forest. Some structures made out of mobile shipping containers equipt with ecological [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mission_statement_and_aims2 {
            get {
                return ResourceManager.GetString("mission_statement_and_aims2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On The Brink Of Extinction.
        /// </summary>
        public static string OnTheBrinkOfExtinctionTitle {
            get {
                return ResourceManager.GetString("OnTheBrinkOfExtinctionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///		padding: 0;
        ///		font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///		font-size: 100%;
        ///		text-rendering: optimizeLegibility !important;
        ///		-webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Your password has been reset. Please [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PasswordResetEmail {
            get {
                return ResourceManager.GetString("PasswordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5&gt;Simon Glantz is practitoner of holistic nutrition, musician and software developer.&lt;/h5&gt;
        ///&lt;p&gt;
        ///	Simon suffered with severe neurological dysfunction from an early age and continued to struggle well into his adult life. Simon used the principles of person-centered nutrition and supplementation,
        ///	as well as many other holistic and traditional healing modalities, to fully recover his mental and physical health and now teaches holistic nutrition, which is taylored to the individual&apos;s genotype, circumstances [rest of string was truncated]&quot;;.
        /// </summary>
        public static string simon_text {
            get {
                return ResourceManager.GetString("simon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software developer, holistic nutritionist and health coach.
        /// </summary>
        public static string simon_title {
            get {
                return ResourceManager.GetString("simon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Puppydog Software&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    .text
        ///    {{
        ///        font-family: lucida grande, Segoe UI, arial, verdana, lucida sans unicode, tahoma, sans-serif; 
        ///        margin: 0; 
        ///        font-size: 10pt; 
        ///        color: #333399;
        ///        padding-bottom: 12px;
        ///    }}
        ///    .title
        ///    {{
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SupportQuery {
            get {
                return ResourceManager.GetString("SupportQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///		padding: 0;
        ///		font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///		font-size: 100%;
        ///		text-rendering: optimizeLegibility !important;
        ///		-webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Thank you for registering with {Comp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeEmail {
            get {
                return ResourceManager.GetString("WelcomeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5&gt;Yann Guignon is the founder of “Blessings Of The Forest” and the main driver of our strategic direction, managing all our activities in Gabon.&lt;/h5&gt;
        ///&lt;p&gt;
        ///	He was initiated to the Gabonese traditions, first in 2006 by Master Atome Ribenga, and was trained to exercise the traditional function of ” Kambo ” (Temple Guardian) by Ribenga and also by Hugues Obiang Poitevin (Ebando NGOs) as well as with other initiatory masters of different branches of the Bwiti. Yann studied iboga intensively and worked with t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string yann_text {
            get {
                return ResourceManager.GetString("yann_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director and founder of Blessings Of The Forest.
        /// </summary>
        public static string yann_title {
            get {
                return ResourceManager.GetString("yann_title", resourceCulture);
            }
        }
    }
}
